hyperparameter_optimization:
  n_trials: 30
  parameters:
    learning_rate:
      min: 1e-5
      max: 1e-1
      type: "log_uniform"
    batch_size:
      values: [16, 32, 64]
      type: "categorical"
    optimizer:
      values: ["Adam"]
      type: "categorical"
    weight_decay:
      min: 1e-5
      max: 1e-5
    num_epochs: 
      min: 5
      max: 20
      type: "int"
augmentation:
  noise: 0.5
  blur: 0.5

offline_augmentation:
  augmentation:
    flip: 1
    mask: 1
    brightness_contrast: 1
  ratio: 2

randaugment:
  num_ops: 3
  magnitude: 4